Add support for nested dependencies

diff --git a/scripts/dr_sync b/scripts/dr_sync
--- a/scripts/dr_sync
+++ b/scripts/dr_sync
@@ -69,12 +69,16 @@ function clone_repo()
   local config_file=$1
   local url=$2
   local name=`get_depend_value "name" $config_file`
+  local depends_path=$3
   if [ -d $name ]; then
     cd $name
     git pull
     cd ..
   else
-    git clone $url $name
+    if [ "$depends_path" == "" ]; then
+      depends_path=.
+    fi
+    git clone $url $depends_path/$name
     local commit=`get_depend_value "commit" $config_file`
     local tag=`get_depend_value "tag" $config_file`
 
@@ -99,12 +103,133 @@ function clone_repo()
 
 function copy_local()
 {
-  cp -r $2 ./
+  local config_file=$1
+  local url=$2
+  local depends_path=$3
+  echo -n "copying local repo:"$2"..."
+  if [ "$depends_path" == "" ]; then
+    depends_path=.
+  fi
+  cp -r $2 $depends_path/
+  echo "done."
 }
 
 function download_from_ftp()
 {
   echo "download_from_ftp"
+}
+
+function sync_sub_repo()
+{
+  local workspace=`pwd`
+  local project=$1
+  local project_name
+  local root_depends_path=$2
+  local root_depends_name=$3
+  local depends_path
+
+  echo root_depends_path:$root_depends_path
+
+  echo -n "Checing workspace..."
+
+  if [ "$project" == "" ]; then
+    project="."
+  fi
+
+  if [ ! -d $project ]; then
+    echo "Project $project not found."
+    return 1
+  fi
+
+  check_dr_project $project
+  if [ $? -eq 1 ]; then
+    echo "Not a dr project."
+    return 1
+  fi
+
+  echo "done."
+
+  echo "Analysising $g_config..."
+  cd $project
+
+  project_name=`get_config_value "name" $g_config`
+  depends_path=`get_config_value "path" $g_config`
+
+  if [ "$depends_path" != "null"  ]; then
+    if [ ! -d $depends_path ]; then
+      mkdir -p $depends_path
+    fi
+  fi
+
+  cd $depends_path
+
+  local rlt=""
+  local index=0
+  while [ "$rlt" != "null" ]
+  do
+    local pattern=".depends[$index]"
+    local one_depend=`jq -r $pattern ../$g_config`
+    rlt="$one_depend"
+    if [ "$rlt" != "null" ];then
+      local cache_file="cache.json"
+      echo $one_depend > $cache_file
+      local name=`get_depend_value "name" $cache_file`
+      mv $cache_file $name.json
+      cache_file=$name.json
+      echo "Depend [$name] found:"
+      add_sub_str="add_subdirectory($root_depends_name/$name)"
+      if [ `grep -c "$add_sub_str" $root_depends_path/../$g_cmake` -eq '0' ];then
+        echo $add_sub_str >> $root_depends_path/../$g_cmake
+      fi
+      local url=`get_depend_value "url" $cache_file`
+      if [ "$url" != "null" ] && [ "$url" != "" ];then
+        if [ -L $name ]; then
+          rm -f $name
+        fi
+        clone_repo $cache_file $url $root_depends_path
+        ln -s $root_depends_path/$name $name
+        check_dr_project $name
+        if [ $? -eq 0 ]; then
+          sync_sub_repo $name $root_depends_path $root_depends_name
+        fi
+        index=`expr $index + 1`
+        continue
+      fi
+
+      local local=`get_depend_value "local" $cache_file`
+      if [ "$local" != "null" ] && [ "$local" != ""  ];then
+        if [ -L $name ]; then
+          rm -f $name
+        fi
+        copy_local $cache_file $local $root_depends_path
+        ln -s $root_depends_path/$name $name
+        check_dr_project $name
+        if [ $? -eq 0 ]; then
+          sync_sub_repo $name $root_depends_path $root_depends_name
+        fi
+        index=`expr $index + 1`
+        continue
+      fi
+
+      local ftp=`get_depend_value "ftp" $cache_file`
+      if [ "$ftp" != "null" ] && [ "$ftp" != ""  ];then
+        download_from_ftp $cache_file $ftp $root_depends_path
+        check_dr_project $name
+        if [ $? -eq 0 ]; then
+          sync_sub_repo $name $root_depends_path $root_depends_name
+        fi
+        ln -s $root_depends_path/$name $name
+        index=`expr $index + 1`
+        continue
+      fi
+    fi
+    index=`expr $index + 1`
+  done
+
+  cd ..
+
+  cd $workspace
+  echo "Finished to sync project $project_name."
 }
 
 function sync_repo()
@@ -135,6 +260,7 @@ function sync_repo()
 
   echo "Analysising $g_config..."
   cd $project
+
   project_name=`get_config_value "name" $g_config`
   depends_path=`get_config_value "path" $g_config`
 
@@ -155,9 +281,11 @@ function sync_repo()
     local one_depend=`jq -r $pattern ../$g_config`
     rlt="$one_depend"
     if [ "$rlt" != "null" ];then
-      local cache_file=$index.json
+      local cache_file="cache.json"
       echo $one_depend > $cache_file
       local name=`get_depend_value "name" $cache_file`
+      mv $cache_file $name.json
+      cache_file=$name.json
       echo "Depend [$name] found:"
       echo "add_subdirectory($depends_path/$name)" >> ../$g_cmake
       local url=`get_depend_value "url" $cache_file`
@@ -165,7 +293,7 @@ function sync_repo()
         clone_repo $cache_file $url
         check_dr_project $name
         if [ $? -eq 0 ]; then
-          sync_repo $name
+          sync_sub_repo $name `pwd` $depends_path
         fi
         index=`expr $index + 1`
         continue
@@ -176,7 +304,7 @@ function sync_repo()
         copy_local $cache_file $local
         check_dr_project $name
         if [ $? -eq 0 ]; then
-          sync_repo $name
+          sync_sub_repo $name `pwd` $depends_path
         fi
         index=`expr $index + 1`
         continue
@@ -187,7 +315,7 @@ function sync_repo()
         download_from_ftp $cache_file $ftp
         check_dr_project $name
         if [ $? -eq 0 ]; then
-          sync_repo $name
+          sync_sub_repo $name `pwd` $depends_path
         fi
         index=`expr $index + 1`
         continue
@@ -206,6 +334,10 @@ function sync_repo()
 
 function main()
 {
+  if [ $# -gt 1 ]; then
+    echo "too many arguments."
+    return 1
+  fi
   sync_repo $@
 }
 
